SELECT 
    a.nama as proyek,
    (select count(x.id) from customer x inner join bank y on x.id_bank=y.id inner join bank_induk z on y.id_bank_induk=z.id where x.id_proyek=a.id and YEAR(x.jadwal_akad)=2025 and x.is_batal=0 and z.nama_bank='BNI' and x.id_metode_pembayaran in (1,2,3,4) ) as BNI,
    (select count(x.id) from customer x inner join bank y on x.id_bank=y.id inner join bank_induk z on y.id_bank_induk=z.id where x.id_proyek=a.id and YEAR(x.jadwal_akad)=2025 and x.is_batal=0 and z.nama_bank='BTN' and x.id_metode_pembayaran in (1,2,3,4) ) as BTN,
    (select count(x.id) from customer x inner join bank y on x.id_bank=y.id inner join bank_induk z on y.id_bank_induk=z.id where x.id_proyek=a.id and YEAR(x.jadwal_akad)=2025 and x.is_batal=0 and z.nama_bank='MANDIRI' and x.id_metode_pembayaran in (1,2,3,4) ) as MANDIRI,
    (select count(x.id) from customer x inner join bank y on x.id_bank=y.id inner join bank_induk z on y.id_bank_induk=z.id where x.id_proyek=a.id and YEAR(x.jadwal_akad)=2025 and x.is_batal=0 and z.nama_bank='BRI' and x.id_metode_pembayaran in (1,2,3,4) ) as BRI,
    (select count(x.id) from customer x inner join bank y on x.id_bank=y.id inner join bank_induk z on y.id_bank_induk=z.id where x.id_proyek=a.id and YEAR(x.jadwal_akad)=2025 and x.is_batal=0 and z.nama_bank='BSI' and x.id_metode_pembayaran in (1,2,3,4) ) as BSI,
    (select count(x.id) from customer x inner join bank y on x.id_bank=y.id inner join bank_induk z on y.id_bank_induk=z.id where x.id_proyek=a.id and YEAR(x.jadwal_akad)=2025 and x.is_batal=0 and z.nama_bank='BJB' and x.id_metode_pembayaran in (1,2,3,4) ) as BJB,
    (select count(x.id) from customer x inner join bank y on x.id_bank=y.id inner join bank_induk z on y.id_bank_induk=z.id where x.id_proyek=a.id and YEAR(x.jadwal_akad)=2025 and x.is_batal=0 and z.nama_bank='BCA' and x.id_metode_pembayaran in (1,2,3,4) ) as BCA,
    (select count(x.id) from customer x inner join bank y on x.id_bank=y.id inner join bank_induk z on y.id_bank_induk=z.id where x.id_proyek=a.id and YEAR(x.jadwal_akad)=2025 and x.is_batal=0 and z.nama_bank='ARTHA GRAHA' and x.id_metode_pembayaran in (1,2,3,4) ) as ARTHA_GRAHA,
    (select count(x.id) from customer x inner join bank y on x.id_bank=y.id inner join bank_induk z on y.id_bank_induk=z.id where x.id_proyek=a.id and YEAR(x.jadwal_akad)=2025 and x.is_batal=0 and z.nama_bank='BANK JATENG' and x.id_metode_pembayaran in (1,2,3,4) ) as BANK_JATENG,
    (select count(x.id) from customer x inner join bank y on x.id_bank=y.id inner join bank_induk z on y.id_bank_induk=z.id where x.id_proyek=a.id and YEAR(x.jadwal_akad)=2025 and x.is_batal=0 and z.nama_bank='BJB SYARIAH' and x.id_metode_pembayaran in (1,2,3,4) ) as BJB_SYARIAH,
    (select count(x.id) from customer x inner join bank y on x.id_bank=y.id inner join bank_induk z on y.id_bank_induk=z.id where x.id_proyek=a.id and YEAR(x.jadwal_akad)=2025 and x.is_batal=0 and z.nama_bank='BANK DKI' and x.id_metode_pembayaran in (1,2,3,4) ) as BANK_DKI,
    (select count(x.id) from customer x inner join bank y on x.id_bank=y.id inner join bank_induk z on y.id_bank_induk=z.id where x.id_proyek=a.id and YEAR(x.jadwal_akad)=2025 and x.is_batal=0 and z.nama_bank='MUAMALAT' and x.id_metode_pembayaran in (1,2,3,4) ) as MUAMALAT,
    (select count(x.id) from customer x inner join bank y on x.id_bank=y.id inner join bank_induk z on y.id_bank_induk=z.id where x.id_proyek=a.id and YEAR(x.jadwal_akad)=2025 and x.is_batal=0 and z.nama_bank='BANK NTB SYARIAH' and x.id_metode_pembayaran in (1,2,3,4) ) as BANK_NTB_SYARIAH,
    (select count(x.id) from customer x inner join bank y on x.id_bank=y.id inner join bank_induk z on y.id_bank_induk=z.id where x.id_proyek=a.id and YEAR(x.jadwal_akad)=2025 and x.is_batal=0 and z.nama_bank='BSB SYARIAH' and x.id_metode_pembayaran in (1,2,3,4) ) as BSB_SYARIAH,
    (select count(x.id) from customer x inner join bank y on x.id_bank=y.id inner join bank_induk z on y.id_bank_induk=z.id where x.id_proyek=a.id and YEAR(x.jadwal_akad)=2025 and x.is_batal=0 and z.nama_bank='BELUM PILIH BANK' and x.id_metode_pembayaran in (1,2,3,4) ) as BELUM_PILIH_BANK,
    (select count(x.id) from customer x inner join bank y on x.id_bank=y.id inner join bank_induk z on y.id_bank_induk=z.id where x.id_proyek=a.id and YEAR(x.jadwal_akad)=2025 and x.is_batal=0 and z.nama_bank='BTN Syariah' and x.id_metode_pembayaran in (1,2,3,4) ) as BTN_Syariah
FROM proyek a